# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# application configuration
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
application.name = 'SE-1 Ordering System'
application.version = 1.0.0
application.args = A BB CCC
application.greeting = true
# application.log-test = true

# run classes that implement the 'R' interface
# application.run = application.Application, application.Demo_1, application.Demo_1, application.Application
# all, first-only
application.run.policy = first-only
# application.banner = true
# 
# CommandLineRunnerImpl.args = sum x=1 y= 2 name = "Max Müller" plz=09130 a b c
application.Demo_1.args = sum x=1 y=2 findFirst z= [ 36, 948, 98 ] x = " 43 39 " y=23 
# application.Demo_1.args = 


# theshold: OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# configure 'Runtime' logger
logger.Runtime.threshold = ALL
logger.Runtime.appenders = logs/runtime.log
# configure 'Demo_1' logger
logger.Demo_1.threshold = ALL
logger.Demo_1.appenders = logs/runtime.log
